// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: LED

#include "../ui.h"

void ui_Index_screen_init(void)
{
    ui_Index = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Index, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Index, lv_color_hex(0x1E2A31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Index, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Index);
    lv_obj_set_width(ui_Panel1, 480);
    lv_obj_set_height(ui_Panel1, lv_pct(78));
    lv_obj_set_align(ui_Panel1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x22313A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Index);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, lv_pct(100));
    lv_obj_set_height(ui_Container3, lv_pct(100));
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel2, 430);
    lv_obj_set_height(ui_Panel2, 130);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, 40);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x2B3C46), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Panel2);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Container1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container1, 10);
    lv_obj_set_y(ui_Container1, 10);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp_label = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_temp_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_temp_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp_label, "28.5 °C");
    lv_obj_set_style_text_color(ui_temp_label, lv_color_hex(0x02DBC5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp_label, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp_status_badge = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_temp_status_badge, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_temp_status_badge, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_temp_status_badge, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_temp_status_badge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_temp_status_badge, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_temp_status_badge, lv_color_hex(0x2CC56F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_temp_status_badge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_temp_status_badge, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_temp_status_badge, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_temp_status_badge, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_temp_status_badge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_temp_status_badge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_temp_status_badge, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp_status_badge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp_status_label = lv_label_create(ui_temp_status_badge);
    lv_obj_set_width(ui_temp_status_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp_status_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_temp_status_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp_status_label, "ปกติ");
    lv_obj_set_style_text_font(ui_temp_status_label, &ui_font_Kanit18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp_chart = lv_chart_create(ui_Panel2);
    lv_obj_set_height(ui_temp_chart, 77);
    lv_obj_set_width(ui_temp_chart, lv_pct(100));
    lv_obj_set_align(ui_temp_chart, LV_ALIGN_BOTTOM_MID);
    lv_chart_set_type(ui_temp_chart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_temp_chart, 600);
    lv_chart_set_div_line_count(ui_temp_chart, 0, 0);
    lv_chart_set_axis_tick(ui_temp_chart, LV_CHART_AXIS_PRIMARY_X, 0, 0, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_temp_chart, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_temp_chart, LV_CHART_AXIS_SECONDARY_Y, 0, 5, 0, 2, false, 25);
    lv_obj_set_style_radius(ui_temp_chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_temp_chart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_temp_chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_temp_chart, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_size(ui_temp_chart, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel4, 430);
    lv_obj_set_height(ui_Panel4, 130);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, 182);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x2B3C46), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel4, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Container2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container2, 10);
    lv_obj_set_y(ui_Container2, 10);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humi_label = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_humi_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humi_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_humi_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humi_label, "60 %RH");
    lv_obj_set_style_text_color(ui_humi_label, lv_color_hex(0xFFC021), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humi_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humi_label, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humi_status_badge = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_humi_status_badge, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_humi_status_badge, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_humi_status_badge, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_humi_status_badge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_humi_status_badge, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_humi_status_badge, lv_color_hex(0x2CC56F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_humi_status_badge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_humi_status_badge, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_humi_status_badge, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_humi_status_badge, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_humi_status_badge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_humi_status_badge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_humi_status_badge, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humi_status_badge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humi_status_label = lv_label_create(ui_humi_status_badge);
    lv_obj_set_width(ui_humi_status_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humi_status_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_humi_status_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humi_status_label, "ปกติ");
    lv_obj_set_style_text_font(ui_humi_status_label, &ui_font_Kanit18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humi_chart = lv_chart_create(ui_Panel4);
    lv_obj_set_height(ui_humi_chart, 77);
    lv_obj_set_width(ui_humi_chart, lv_pct(100));
    lv_obj_set_align(ui_humi_chart, LV_ALIGN_BOTTOM_MID);
    lv_chart_set_type(ui_humi_chart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_humi_chart, 600);
    lv_chart_set_div_line_count(ui_humi_chart, 0, 0);
    lv_chart_set_axis_tick(ui_humi_chart, LV_CHART_AXIS_PRIMARY_X, 0, 0, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_humi_chart, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_humi_chart, LV_CHART_AXIS_SECONDARY_Y, 0, 5, 0, 2, false, 25);
    lv_obj_set_style_radius(ui_humi_chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_humi_chart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_humi_chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_humi_chart, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_size(ui_humi_chart, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);


}
